version: '3'
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=1234"
  backend:
    image: "configset-backend"
    ports:
      - "5554:5554"
    environment:
      - "db_type=postgres"
      - "authenticator_type=oauth"
      - "oauth_provider_url=http://keycloack:8080/auth/realms/demo/protocol/openid-connect/userinfo"
      - "jdbc_url=jdbc:postgresql://db:5432/postgres?user=postgres&password=1234"
      - "log.level=DEBUG"
  dashboard:
    image: "configset-dashboard-dev"
    ports:
      - "8188:8188"
      - "5555:5555"
    environment:
      - "config_server.hostname=backend"
      - "config_server.port=8080"
      - "client.keycloackUrl=http://localhost:8077"
      - "client.keycloackRealm=demo"
      - "client.keycloackClientId=demo-clientId"
  keycloack:
    image: "quay.io/keycloak/keycloak:15.0.1"
    ports:
      - "8077:8080"
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
